# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'pt-pal-frontend'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
- task: AzureFileCopy@2
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
    azureSubscription: 'Free Trial(eb3ba4ad-1f4e-4ad4-b676-7c4a3dfe7925)'
    Destination: 'AzureBlob'
    storage: 'ptester'
    ContainerName: '$web'
- script: |
    dotnet restore
    dotnet build --configuration Release
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'pt-pal.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/pt-pal-backend/bin/Debug/netcoreapp2.1/bin"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    ArtifactName: 'drop'
    publishLocation: "Filepath"
    TargetPath: "$(System.DefaultWorkingDirectory)/publish/$(Build.BuildId).zip"
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Free Trial(eb3ba4ad-1f4e-4ad4-b676-7c4a3dfe7925)'
    appType: 'functionApp'
    appName: 'pt-pal'
    package: "$(System.DefaultWorkingDirectory)/publish/$(Build.BuildId).zip"
    deploymentMethod: 'auto'